logging:
  level:
    com.atomist.spring.agent: DEBUG

atomist:
  enabled: true
  debug: true
  url: 'https://webhook.atomist.com/atomist/application/teams/${ATOMIST_WORKSPACE:${random.value}}'
  environment:
    domain: '${ATOMIST_ENVIRONMENT:${vcap.application.space_name:local}}'
    pod: '${HOSTNAME:${random.value}}'

raven: 
  dsn: 'https://03cfa203669f42118c981909c1517826@sentry.io/1214452'
